### ISSUE TITLE
Invalid Grant: exp claim exceeds the maximum value when getting tokens via JWT

### ISSUE THREAD

**Issue by hawkins** [cburnette/boxr#69]
When trying to get tokens via JWT, I receive the following error:

```
Traceback (most recent call last):
lib/boxr/auth.rb:32:in `get_enterprise_token'
lib/boxr/auth.rb:24:in `get_tokens'
lib/boxr/auth.rb:92:in `auth_post': 400: {
  "error": "invalid_grant",
  "error_description": "Please check the 'exp' claim. The 'exp' value exceeds the maximum value of 60 seconds beyond the issue time."
} (Boxr::BoxrError)
```

The expiry time looks to be hardcoded as 10 seconds in the future, and it doesn't take even ~2 seconds to make this request after setting that expiry time. Why does this happen then?

For reference, I'm roughly following [this guide](https://developer.box.com/docs/authenticate-with-jwt). My environment variables are loaded from a typical `.env`, which looks like this:

```env
BOX_CLIENT_ID="..."
BOX_CLIENT_SECRET="..."
BOX_ENTERPRISE_ID="..."
JWT_PUBLIC_KEY_ID="..."
JWT_PRIVATE_KEY="-----BEGIN ENCRYPTED PRIVATE KEY-----\n..."
JWT_PRIVATE_KEY_PASSWORD="..."
```

The code I'm running is as follows:

```ruby
require 'dotenv/load'
require 'boxr'

tokens = Boxr::get_enterprise_token  # <-- error from underlying auth_post
box = Boxr::Client.new(tokens.access_token)
```

Am I using private keys incorrectly, or is there something else at play?

**Comment by hawkins** [comment]
Looks like my NTP server is two minutes fast, so when I specified `exp: Time.now.utc -100`, it was accepted and gave me a JWT.

Closing this as its my network configuration issue. Sorry!
